#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
echo "Cleaning temporary files"
./cleanTempFiles
cd $DIR/examples
echo "Running catcher!"
node testCarController.js > carcontroller.log
